-- Sales Store ELT
-- Catalog: sales_store
-- Schema: linio
-- Storage account: stsalesstoresergio
-- Container: sales-store

CREATE SCHEMA IF NOT EXISTS sales_store.linio;


-- ============================================================
-- BRONZE LAYER
-- ============================================================

CREATE TABLE sales_store.linio.bronze_compras (
    venta_id STRING,
    factura STRING,
    fecha_orden STRING,
    fecha_entrega STRING,
    fecha_envio STRING,
    estado STRING,
    cliente_code STRING,
    tipo_cliente STRING,
    nombres STRING,
    apellidos STRING,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    subtotal STRING,
    tipo_compra STRING,
    fecha_carga TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/bronze/compras';

CREATE TABLE sales_store.linio.bronze_detalles (
    detalle_id STRING,
    factura STRING,
    categoria STRING,
    subcategoria STRING,
    producto STRING,
    unidades STRING,
    precio_unitario STRING,
    oferta_id STRING,
    nombre_archivo STRING,
    fecha_carga TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/bronze/detalles';

-- ============================================================
-- SILVER LAYER
-- ============================================================

CREATE TABLE sales_store.linio.silver_compras (
    venta_id INTEGER,
    factura STRING,
    tipo_compra STRING,
    fecha_orden DATE,
    fecha_entrega DATE,
    fecha_envio DATE,
    estado INTEGER,
    cliente_id INTEGER,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    dias_envio INTEGER,
    grupo_dias_envio STRING,
    periodo DATE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/silver/compras';

CREATE TABLE sales_store.linio.silver_clientes (
    cliente_id INTEGER,
    tipo_documento STRING,
    num_documento STRING,
    nombre_completo STRING,
    tipo_cliente STRING,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/silver/clientes';

CREATE TABLE sales_store.linio.silver_productos (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    producto STRING,
    categoria STRING,
    subcategoria STRING,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT silver_productos_pk PRIMARY KEY (producto_id)
)
USING DELTA
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/silver/productos';

CREATE TABLE sales_store.linio.silver_detalles (
    detalle_id INTEGER,
    factura STRING,
    producto STRING,
    producto_id BIGINT,
    unidades INTEGER,
    precio_unitario DOUBLE,
    subtotal DOUBLE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/silver/detalles';

-- ============================================================
-- GOLD LAYER
-- ============================================================

CREATE VIEW sales_store.linio.gold_dim_clientes AS
SELECT
    cliente_id,
    tipo_documento,
    num_documento,
    nombre_completo,
    tipo_cliente
FROM sales_store.linio.silver_clientes;

CREATE VIEW sales_store.linio.gold_dim_productos AS
SELECT
    producto_id,
    producto,
    categoria,
    subcategoria
FROM sales_store.linio.silver_productos;

CREATE TABLE sales_store.linio.gold_fact_compras (
    periodo DATE,
    venta_id INTEGER,
    factura STRING,
    tipo_compra STRING,
    fecha_orden DATE,
    fecha_entrega DATE,
    fecha_envio DATE,
    estado INTEGER,
    cliente_id INTEGER,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    grupo_dias_envio STRING,
    detalle_id INTEGER,
    producto_id BIGINT,
    unidades INTEGER,
    subtotal DOUBLE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@stsalesstoresergio.dfs.core.windows.net/gold/fact_compras';
